# Code generated by servicegen from dependencies.yaml. DO NOT EDIT.

VERSIONS = {
    "abseil": "20260526.0",
    "asio-grpc": "3.5.0",
    "boost": "1.89.0",
    "conan": "2.31.1",
    "googletest": "1.15.2",
    "grpc": "1.83.1",
    "jemalloc": "5.3.1",
    "libcron": "1.3.3",
    "librdkafka": "2.8.0",
    "openssl": "3.6.3",
    "opentelemetry-cpp": "1.20.0",
    "opentelemetry-proto": "1.5.0",
    "protobuf": "6.33.5",
    "re2": "20251105",
    "yaml-cpp": "0.8.0",
}

REPOSITORIES = {
    "abseil": "https://github.com/abseil/abseil-cpp",
    "asio-grpc": "https://github.com/Tradias/asio-grpc",
    "boost": "https://github.com/boostorg/boost",
    "c-ares": "https://github.com/c-ares/c-ares",
    "googletest": "https://github.com/google/googletest",
    "grpc": "https://github.com/grpc/grpc",
    "grpc-protobuf": "https://github.com/protocolbuffers/protobuf",
    "libcron": "https://github.com/PerMalmberg/libcron",
    "libcron-date": "https://github.com/HowardHinnant/date",
    "librdkafka": "https://github.com/confluentinc/librdkafka",
    "opencensus-proto": "https://github.com/census-instrumentation/opencensus-proto",
    "opentelemetry-cpp": "https://github.com/open-telemetry/opentelemetry-cpp",
    "opentelemetry-proto": "https://github.com/open-telemetry/opentelemetry-proto",
    "protobuf": "https://github.com/protocolbuffers/protobuf",
    "re2": "https://github.com/google/re2",
    "yaml-cpp": "https://github.com/jbeder/yaml-cpp",
}

REVISIONS = {
    "abseil": "76bb24329e8bf5f39704eb10d21b9a80befa7c81",
    "asio-grpc": "v3.5.0",
    "boost": "1.89.0",
    "c-ares": "6360e96b5cf8e5980c887ce58ef727e53d77243a",
    "googletest": "v1.15.2",
    "grpc": "v1.83.1",
    "grpc-protobuf": "35cd01f9fe9afbeea38cc7b979a3b6bfcde82c03",
    "libcron": "v1.3.3",
    "libcron-date": "f94b8f36c6180be0021876c4a397a054fe50c6f2",
    "librdkafka": "v2.8.0",
    "opencensus-proto": "v0.3.0",
    "opentelemetry-cpp": "v1.20.0",
    "opentelemetry-proto": "v1.5.0",
    "protobuf": "v33.5",
    "re2": "0c5616df9c0aaa44c9440d87422012423d91c7d1",
    "yaml-cpp": "0.8.0",
}

SHA256 = {
    "googletest": "7b42b4d6ed48810c5362c265a17faebe90dc2373c885e5216439d37927f02926",
    "grpc": "60caa8397426d8a500e3e57ab6a49d1cb5aa62a36f2591eb9da3d77fa38ad8c9",
    "libcron": "7d413b7950c82b54157b2a7f446e1e660bd718e542e2ffd3f8715e467ab2b825",
    "libcron-date": "8be4c3a52d99b22a4478ce3e2a23fa4b38587ea3d3bc3d1a4d68de22c2e65fb2",
    "opentelemetry-cpp": "4b6eeb852f075133c21b95948017f13a3e21740e55b921d27e42970a47314297",
    "opentelemetry-proto": "08f40636adbc5f33d2084bd8e7b64e491dd0239d1a95021dbffbdf1ca8cea454",
}


def version(name: str) -> str:
    return VERSIONS[name]


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2 or sys.argv[1] not in VERSIONS:
        names = ", ".join(sorted(VERSIONS))
        raise SystemExit(f"usage: {sys.argv[0]} <version>; known: {names}")
    print(VERSIONS[sys.argv[1]])
