compiler:
  apple-clang:
    sanitizer: [null, Address, AddressOnly, AddressUndefined, Thread]
  clang:
    sanitizer: [null, Address, AddressOnly, AddressUndefined, Thread]
  gcc:
    sanitizer: [null, Address, AddressOnly, AddressUndefined, Thread]
