// Code generated by api/generate.py from servicelib/api/serviceapi.yaml. DO NOT EDIT.
#pragma once

#include <array>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>

#include <servicelib/api/serviceapi.hpp>
#include <servicelib/runtime/config/yaml_value.hpp>

namespace servicelib::api {
using namespace std::string_view_literals;

namespace detail {

template <typename E, std::size_t N>
E ParseEnum(const config::YamlValue& value,
            const std::array<std::pair<std::string_view, E>, N>& values) {
  const auto text = value.template As<std::string>();
  for (const auto& [name, parsed] : values) {
    if (name == text) {
      return parsed;
    }
  }
  throw std::invalid_argument("unknown enum value: " + text);
}

}  // namespace detail
inline constexpr std::array kProgrammingLanguageMap{
    std::pair{"Undefined"sv, ProgrammingLanguage::kUndefined},
    std::pair{"GoLang"sv, ProgrammingLanguage::kGoLang},
    std::pair{"CppUserver"sv, ProgrammingLanguage::kCppUserver},
    std::pair{"Python"sv, ProgrammingLanguage::kPython},
    std::pair{"Rust"sv, ProgrammingLanguage::kRust},
    std::pair{"CppBoost"sv, ProgrammingLanguage::kCppBoost},
    std::pair{"TypeScript"sv, ProgrammingLanguage::kTypeScript}};

inline ProgrammingLanguage Parse(const config::YamlValue& value,
                         config::TypeTag<ProgrammingLanguage>) {
  return detail::ParseEnum(value, kProgrammingLanguageMap);
}

inline constexpr std::array kJoinStorageTypeMap{
    std::pair{"Undefined"sv, JoinStorageType::kUndefined},
    std::pair{"HashMap"sv, JoinStorageType::kHashMap},
    std::pair{"RocksDB"sv, JoinStorageType::kRocksDB},
    std::pair{"Aerospike"sv, JoinStorageType::kAerospike}};

inline JoinStorageType Parse(const config::YamlValue& value,
                         config::TypeTag<JoinStorageType>) {
  return detail::ParseEnum(value, kJoinStorageTypeMap);
}

inline constexpr std::array kTransformationTypeMap{
    std::pair{"Undefined"sv, TransformationType::kUndefined},
    std::pair{"Input"sv, TransformationType::kInput},
    std::pair{"Map"sv, TransformationType::kMap},
    std::pair{"Filter"sv, TransformationType::kFilter},
    std::pair{"Join"sv, TransformationType::kJoin},
    std::pair{"MultiJoin"sv, TransformationType::kMultiJoin},
    std::pair{"Process"sv, TransformationType::kProcess},
    std::pair{"FlatMap"sv, TransformationType::kFlatMap},
    std::pair{"FlatMapIterable"sv, TransformationType::kFlatMapIterable},
    std::pair{"KeyBy"sv, TransformationType::kKeyBy},
    std::pair{"Merge"sv, TransformationType::kMerge},
    std::pair{"Split"sv, TransformationType::kSplit},
    std::pair{"Case"sv, TransformationType::kCase},
    std::pair{"Sink"sv, TransformationType::kSink},
    std::pair{"CycleLink"sv, TransformationType::kCycleLink},
    std::pair{"Error"sv, TransformationType::kError},
    std::pair{"Delay"sv, TransformationType::kDelay},
    std::pair{"When"sv, TransformationType::kWhen},
    std::pair{"SubStream"sv, TransformationType::kSubStream}};

inline TransformationType Parse(const config::YamlValue& value,
                         config::TypeTag<TransformationType>) {
  return detail::ParseEnum(value, kTransformationTypeMap);
}

inline constexpr std::array kJoinTypeMap{
    std::pair{"Undefined"sv, JoinType::kUndefined},
    std::pair{"Inner"sv, JoinType::kInner},
    std::pair{"Left"sv, JoinType::kLeft},
    std::pair{"Right"sv, JoinType::kRight},
    std::pair{"Outer"sv, JoinType::kOuter}};

inline JoinType Parse(const config::YamlValue& value,
                         config::TypeTag<JoinType>) {
  return detail::ParseEnum(value, kJoinTypeMap);
}

inline constexpr std::array kHTTPMethodTypeMap{
    std::pair{""sv, HTTPMethodType::kUndefined},
    std::pair{"GET"sv, HTTPMethodType::kGET},
    std::pair{"POST"sv, HTTPMethodType::kPOST},
    std::pair{"PUT"sv, HTTPMethodType::kPUT},
    std::pair{"PATCH"sv, HTTPMethodType::kPATCH},
    std::pair{"DELETE"sv, HTTPMethodType::kDELETE},
    std::pair{"HEAD"sv, HTTPMethodType::kHEAD},
    std::pair{"OPTIONS"sv, HTTPMethodType::kOPTIONS},
    std::pair{"TRACE"sv, HTTPMethodType::kTRACE},
    std::pair{"CONNECT"sv, HTTPMethodType::kCONNECT}};

inline HTTPMethodType Parse(const config::YamlValue& value,
                         config::TypeTag<HTTPMethodType>) {
  return detail::ParseEnum(value, kHTTPMethodTypeMap);
}

inline constexpr std::array kGrpcMethodTypeMap{
    std::pair{"Undefined"sv, GrpcMethodType::kUndefined},
    std::pair{"NoStreaming"sv, GrpcMethodType::kNoStreaming},
    std::pair{"ClientStreaming"sv, GrpcMethodType::kClientStreaming},
    std::pair{"ServerStreaming"sv, GrpcMethodType::kServerStreaming},
    std::pair{"BidirectionalStreaming"sv, GrpcMethodType::kBidirectionalStreaming}};

inline GrpcMethodType Parse(const config::YamlValue& value,
                         config::TypeTag<GrpcMethodType>) {
  return detail::ParseEnum(value, kGrpcMethodTypeMap);
}

inline constexpr std::array kCallSemanticsMap{
    std::pair{"Undefined"sv, CallSemantics::kUndefined},
    std::pair{"Inherited"sv, CallSemantics::kInherited},
    std::pair{"FunctionCall"sv, CallSemantics::kFunctionCall},
    std::pair{"TaskPool"sv, CallSemantics::kTaskPool},
    std::pair{"PriorityTaskPool"sv, CallSemantics::kPriorityTaskPool},
    std::pair{"ParallelCall"sv, CallSemantics::kParallelCall}};

inline CallSemantics Parse(const config::YamlValue& value,
                         config::TypeTag<CallSemantics>) {
  return detail::ParseEnum(value, kCallSemanticsMap);
}

inline constexpr std::array kDataConnectorTypeMap{
    std::pair{"Undefined"sv, DataConnectorType::kUndefined},
    std::pair{"HTTP"sv, DataConnectorType::kHTTP},
    std::pair{"gRPC"sv, DataConnectorType::kGRPC},
    std::pair{"Kafka"sv, DataConnectorType::kKafka},
    std::pair{"Custom"sv, DataConnectorType::kCustom},
    std::pair{"Cron"sv, DataConnectorType::kCron},
    std::pair{"Temporal"sv, DataConnectorType::kTemporal}};

inline DataConnectorType Parse(const config::YamlValue& value,
                         config::TypeTag<DataConnectorType>) {
  return detail::ParseEnum(value, kDataConnectorTypeMap);
}

inline constexpr std::array kProcessPatternMap{
    std::pair{"Undefined"sv, ProcessPattern::kUndefined},
    std::pair{"Execute"sv, ProcessPattern::kExecute},
    std::pair{"Collect"sv, ProcessPattern::kCollect}};

inline ProcessPattern Parse(const config::YamlValue& value,
                         config::TypeTag<ProcessPattern>) {
  return detail::ParseEnum(value, kProcessPatternMap);
}

inline constexpr std::array kLogLevelMap{
    std::pair{""sv, LogLevel::kUndefined},
    std::pair{"CRITICAL"sv, LogLevel::kCRITICAL},
    std::pair{"FATAL"sv, LogLevel::kFATAL},
    std::pair{"ERROR"sv, LogLevel::kERROR},
    std::pair{"WARNING"sv, LogLevel::kWARNING},
    std::pair{"INFO"sv, LogLevel::kINFO},
    std::pair{"DEBUG"sv, LogLevel::kDEBUG}};

inline LogLevel Parse(const config::YamlValue& value,
                         config::TypeTag<LogLevel>) {
  return detail::ParseEnum(value, kLogLevelMap);
}

inline constexpr std::array kEnvironmentMap{
    std::pair{""sv, Environment::kUndefined},
    std::pair{"local"sv, Environment::kLocal},
    std::pair{"debug"sv, Environment::kDebug},
    std::pair{"staging"sv, Environment::kStaging},
    std::pair{"production"sv, Environment::kProduction}};

inline Environment Parse(const config::YamlValue& value,
                         config::TypeTag<Environment>) {
  return detail::ParseEnum(value, kEnvironmentMap);
}

inline constexpr std::array kKubernetesWorkloadTypeMap{
    std::pair{"Deployment"sv, KubernetesWorkloadType::kDeployment},
    std::pair{"StatefulSet"sv, KubernetesWorkloadType::kStatefulSet}};

inline KubernetesWorkloadType Parse(const config::YamlValue& value,
                         config::TypeTag<KubernetesWorkloadType>) {
  return detail::ParseEnum(value, kKubernetesWorkloadTypeMap);
}

inline constexpr std::array kDataConnectorImplementationMap{
    std::pair{""sv, DataConnectorImplementation::kUndefined},
    std::pair{"net/http"sv, DataConnectorImplementation::kNetHTTP},
    std::pair{"function"sv, DataConnectorImplementation::kFunction},
    std::pair{"IBM/Sarama"sv, DataConnectorImplementation::kIBMsarama},
    std::pair{"google/grpc"sv, DataConnectorImplementation::kGoogleGRPC},
    std::pair{"userver/http"sv, DataConnectorImplementation::kUserverHTTP},
    std::pair{"userver/grpc"sv, DataConnectorImplementation::kUserverGRPC},
    std::pair{"userver/kafka"sv, DataConnectorImplementation::kUserverKafka},
    std::pair{"boost/beast-http"sv, DataConnectorImplementation::kBoostBeastHTTP},
    std::pair{"asio/grpc"sv, DataConnectorImplementation::kAsioGRPC},
    std::pair{"librdkafka"sv, DataConnectorImplementation::kLibrdkafka},
    std::pair{"aiohttp"sv, DataConnectorImplementation::kAioHTTP},
    std::pair{"aiokafka"sv, DataConnectorImplementation::kAioKafka},
    std::pair{"rust/axum"sv, DataConnectorImplementation::kRustAxum},
    std::pair{"rust/tonic"sv, DataConnectorImplementation::kRustTonic},
    std::pair{"rust/rdkafka"sv, DataConnectorImplementation::kRustRdkafka},
    std::pair{"node/http"sv, DataConnectorImplementation::kNodeHTTP},
    std::pair{"grpc/grpc-js"sv, DataConnectorImplementation::kGrpcJS},
    std::pair{"confluent/kafka-javascript"sv, DataConnectorImplementation::kConfluentKafkaJavaScript},
    std::pair{"go/gocron"sv, DataConnectorImplementation::kGoGocron},
    std::pair{"python/apscheduler"sv, DataConnectorImplementation::kPythonAPScheduler},
    std::pair{"rust/croner"sv, DataConnectorImplementation::kRustCroner},
    std::pair{"node/croner"sv, DataConnectorImplementation::kNodeCroner},
    std::pair{"cpp/libcron"sv, DataConnectorImplementation::kCppLibcron},
    std::pair{"temporal/go"sv, DataConnectorImplementation::kTemporalGo},
    std::pair{"temporal/python"sv, DataConnectorImplementation::kTemporalPython},
    std::pair{"temporal/typescript"sv, DataConnectorImplementation::kTemporalTypeScript}};

inline DataConnectorImplementation Parse(const config::YamlValue& value,
                         config::TypeTag<DataConnectorImplementation>) {
  return detail::ParseEnum(value, kDataConnectorImplementationMap);
}

inline constexpr std::array kKafkaSecurityProtocolMap{
    std::pair{"PLAINTEXT"sv, KafkaSecurityProtocol::kPLAINTEXT},
    std::pair{"SASL_PLAINTEXT"sv, KafkaSecurityProtocol::kSASLPLAINTEXT},
    std::pair{"SASL_SSL"sv, KafkaSecurityProtocol::kSASLSSL}};

inline KafkaSecurityProtocol Parse(const config::YamlValue& value,
                         config::TypeTag<KafkaSecurityProtocol>) {
  return detail::ParseEnum(value, kKafkaSecurityProtocolMap);
}

inline constexpr std::array kKafkaSaslMechanismMap{
    std::pair{"PLAIN"sv, KafkaSaslMechanism::kPLAIN},
    std::pair{"SCRAM-SHA-256"sv, KafkaSaslMechanism::kSCRAMSHA256},
    std::pair{"SCRAM-SHA-512"sv, KafkaSaslMechanism::kSCRAMSHA512}};

inline KafkaSaslMechanism Parse(const config::YamlValue& value,
                         config::TypeTag<KafkaSaslMechanism>) {
  return detail::ParseEnum(value, kKafkaSaslMechanismMap);
}

inline constexpr std::array kScheduleOverlapPolicyMap{
    std::pair{"Allow"sv, ScheduleOverlapPolicy::kAllow},
    std::pair{"Skip"sv, ScheduleOverlapPolicy::kSkip}};

inline ScheduleOverlapPolicy Parse(const config::YamlValue& value,
                         config::TypeTag<ScheduleOverlapPolicy>) {
  return detail::ParseEnum(value, kScheduleOverlapPolicyMap);
}

inline constexpr std::array kScheduleMissedRunPolicyMap{
    std::pair{"Skip"sv, ScheduleMissedRunPolicy::kSkip},
    std::pair{"FireOnce"sv, ScheduleMissedRunPolicy::kFireOnce}};

inline ScheduleMissedRunPolicy Parse(const config::YamlValue& value,
                         config::TypeTag<ScheduleMissedRunPolicy>) {
  return detail::ParseEnum(value, kScheduleMissedRunPolicyMap);
}

inline constexpr std::array kTemporalExecutionTypeMap{
    std::pair{"Activity"sv, TemporalExecutionType::kActivity},
    std::pair{"Workflow"sv, TemporalExecutionType::kWorkflow}};

inline TemporalExecutionType Parse(const config::YamlValue& value,
                         config::TypeTag<TemporalExecutionType>) {
  return detail::ParseEnum(value, kTemporalExecutionTypeMap);
}

inline constexpr std::array kTypeDefinitionFormatMap{
    std::pair{"Undefined"sv, TypeDefinitionFormat::kUndefined},
    std::pair{"Native"sv, TypeDefinitionFormat::kNative},
    std::pair{"Protobuf"sv, TypeDefinitionFormat::kProtobuf},
    std::pair{"FlatBuffers"sv, TypeDefinitionFormat::kFlatBuffers},
    std::pair{"CapNProto"sv, TypeDefinitionFormat::kCapNProto},
    std::pair{"OpenAPI"sv, TypeDefinitionFormat::kOpenAPI}};

inline TypeDefinitionFormat Parse(const config::YamlValue& value,
                         config::TypeTag<TypeDefinitionFormat>) {
  return detail::ParseEnum(value, kTypeDefinitionFormatMap);
}

inline constexpr std::array kDataTypeMap{
    std::pair{""sv, DataType::kUndefined},
    std::pair{"int"sv, DataType::kInt},
    std::pair{"uint"sv, DataType::kUint},
    std::pair{"byte"sv, DataType::kByte},
    std::pair{"char"sv, DataType::kChar},
    std::pair{"boolean"sv, DataType::kBoolean},
    std::pair{"unicode char"sv, DataType::kUnicodeChar},
    std::pair{"string"sv, DataType::kString},
    std::pair{"unicode string"sv, DataType::kUnicodeString},
    std::pair{"float"sv, DataType::kFloat},
    std::pair{"double"sv, DataType::kDouble},
    std::pair{"int8"sv, DataType::kInt8},
    std::pair{"int16"sv, DataType::kInt16},
    std::pair{"int32"sv, DataType::kInt32},
    std::pair{"int64"sv, DataType::kInt64},
    std::pair{"uint8"sv, DataType::kUint8},
    std::pair{"uint16"sv, DataType::kUint16},
    std::pair{"uint32"sv, DataType::kUint32},
    std::pair{"uint64"sv, DataType::kUint64},
    std::pair{"any"sv, DataType::kAny},
    std::pair{"error"sv, DataType::kError},
    std::pair{"array"sv, DataType::kArray},
    std::pair{"map"sv, DataType::kMap},
    std::pair{"struct"sv, DataType::kStruct},
    std::pair{"custom"sv, DataType::kCustom}};

inline DataType Parse(const config::YamlValue& value,
                         config::TypeTag<DataType>) {
  return detail::ParseEnum(value, kDataTypeMap);
}
}  // namespace servicelib::api
